services:
    # Form types
    
    rk_team_module.form.type.personquicknav:
        class: RK\TeamModule\Form\Type\QuickNavigation\PersonQuickNavType
        arguments: ["@translator.default", "@request_stack", "@rk_team_module.listentries_helper"]
        tags:
            - { name: form.type }
    
    rk_team_module.form.handler.person:
        class: RK\TeamModule\Form\Handler\Person\EditHandler
        arguments: ["@service_container", "@translator.default", "@request_stack", "@router"]
        tags:
            - { name: form.type }
    
    rk_team_module.form.type.person:
        class: RK\TeamModule\Form\Type\PersonType
        arguments: ["@translator.default", "@rk_team_module.person_factory", "@rk_team_module.listentries_helper"]
        tags:
            - { name: form.type }
    
    rk_team_module.form.type.deleteentity:
        class: RK\TeamModule\Form\DeleteEntityType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }
    
    rk_team_module.form.type.block.itemlist:
        class: RK\TeamModule\Block\Form\Type\ItemListBlockType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }
    
    rk_team_module.form.type.personfinder:
        class: RK\TeamModule\Form\Type\Finder\PersonFinderType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }
    
    rk_team_module.form.type.appsettings:
        class: RK\TeamModule\Form\AppSettingsType
        arguments: ["@translator.default", "@zikula_extensions_module.api.variable"]
        tags:
            - { name: form.type }
