services:
    # Upload handler class
    rk_team_module.upload_handler:
        class: RK\TeamModule\UploadHandler
        arguments: ["@translator.default", "@zikula_users_module.current_user", "@zikula_extensions_module.api.variable"]
