services:
    # Entity factory classes
    rk_download_module.file_factory:
        class: RK\DownloadModule\Entity\Factory\FileFactory
        arguments: ["@doctrine.orm.entity_manager", RK\DownloadModule\Entity\FileEntity]
    
