services:
    # Helper classes
    rk_download_module.category_helper:
        class: RK\DownLoadModule\Helper\CategoryHelper
        arguments: ["@service_container", "@translator.default", "@session", "@logger", "@request_stack", "@zikula_users_module.current_user"]
    
    rk_download_module.controller_helper:
        class: RK\DownLoadModule\Helper\ControllerHelper
        arguments: ["@service_container", "@translator.default", "@session", "@logger"]
    
    rk_download_module.feature_activation_helper:
        class: RK\DownLoadModule\Helper\FeatureActivationHelper
    
    rk_download_module.hook_helper:
        class: RK\DownLoadModule\Helper\HookHelper
        arguments: ["@hook_dispatcher"]
    
    rk_download_module.image_helper:
        class: RK\DownLoadModule\Helper\ImageHelper
        arguments: ["@translator.default", "@session", "@zikula_extensions_module.api.variable"]
    
    rk_download_module.listentries_helper:
        class: RK\DownLoadModule\Helper\ListEntriesHelper
        arguments: ["@translator.default"]
    
    rk_download_module.model_helper:
        class: RK\DownLoadModule\Helper\ModelHelper
        arguments: ["@service_container"]
    
    rk_download_module.selection_helper:
        class: RK\DownLoadModule\Helper\SelectionHelper
        arguments: ["@service_container", "@doctrine.orm.entity_manager", "@translator.default", "@rk_download_module.controller_helper"]
    
    rk_download_module.view_helper:
        class: RK\DownLoadModule\Helper\ViewHelper
        arguments: ["@service_container", "@translator.default"]
    
    rk_download_module.workflow_helper:
        class: RK\DownLoadModule\Helper\WorkflowHelper
        arguments: ["@service_container", "@translator.default"]
