services:
    # Upload handler class
    rk_download_module.upload_handler:
        class: RK\DownLoadModule\UploadHandler
        arguments: ["@translator.default", "@zikula_users_module.current_user", "@zikula_extensions_module.api.variable"]
