<?php
/**
 * Sponsoring.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\SponsoringModule\Form\Type;

use RK\SponsoringModule\Form\Type\Base\AbstractSponsorType;

/**
 * Sponsor editing form type implementation class.
 */
class SponsorType extends AbstractSponsorType
{
    // feel free to extend the sponsor editing form type class here
}
