<?php
/**
 * Sponsoring.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\SponsoringModule\Form\Type\Finder;

use RK\SponsoringModule\Form\Type\Finder\Base\AbstractSponsorFinderType;

/**
 * Sponsor finder form type implementation class.
 */
class SponsorFinderType extends AbstractSponsorFinderType
{
    // feel free to extend the base form type class here
}
