<?php
/**
 * ParkHaus.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ParkHausModule\Form\Type\QuickNavigation;

use RK\ParkHausModule\Form\Type\QuickNavigation\Base\AbstractVehicleQuickNavType;

/**
 * Vehicle quick navigation form type implementation class.
 */
class VehicleQuickNavType extends AbstractVehicleQuickNavType
{
    // feel free to extend the base form type class here
}
