<?php
/**
 * Websitehelper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace RK\WebsitehelperModule\ContentType;

use RK\WebsitehelperModule\ContentType\Base\AbstractItem;

/**
 * Generic single item display content plugin implementation class.
 */
class Item extends AbstractItem
{
    // feel free to extend the content type here
}
