services:
    # Form types
    
    rk_parkhaus_module.form.type.vehiclequicknav:
        class: RK\ParkHausModule\Form\Type\QuickNavigation\VehicleQuickNavType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@rk_parkhaus_module.listentries_helper"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.vehicleimagequicknav:
        class: RK\ParkHausModule\Form\Type\QuickNavigation\VehicleImageQuickNavType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@rk_parkhaus_module.listentries_helper"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.handler.vehicle:
        class: RK\ParkHausModule\Form\Handler\Vehicle\EditHandler
        arguments:
            - "@service_container"
            - "@translator.default"
            - "@request_stack"
            - "@router"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.vehicle:
        class: RK\ParkHausModule\Form\Type\VehicleType
        arguments:
            - "@translator.default"
            - "@rk_parkhaus_module.vehicle_factory"
            - "@rk_parkhaus_module.listentries_helper"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.handler.vehicleimage:
        class: RK\ParkHausModule\Form\Handler\VehicleImage\EditHandler
        arguments:
            - "@service_container"
            - "@translator.default"
            - "@request_stack"
            - "@router"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.vehicleimage:
        class: RK\ParkHausModule\Form\Type\VehicleImageType
        arguments:
            - "@translator.default"
            - "@rk_parkhaus_module.vehicleImage_factory"
            - "@rk_parkhaus_module.listentries_helper"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.deleteentity:
        class: RK\ParkHausModule\Form\DeleteEntityType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.block.itemlist:
        class: RK\ParkHausModule\Block\Form\Type\ItemListBlockType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.vehiclefinder:
        class: RK\ParkHausModule\Form\Type\Finder\VehicleFinderType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.vehicleimagefinder:
        class: RK\ParkHausModule\Form\Type\Finder\VehicleImageFinderType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.appsettings:
        class: RK\ParkHausModule\Form\AppSettingsType
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
        tags:
            - { name: form.type }
