services:
    # Twig extension
    rk_parkhaus_module.twig_extension:
        class: RK\ParkHausModule\Twig\TwigExtension
        arguments: ["@translator.default", "@zikula_extensions_module.api.variable", "@rk_parkhaus_module.workflow_helper", "@rk_parkhaus_module.view_helper", "@rk_parkhaus_module.listentries_helper"]
        public: false
        tags:
            - { name: twig.extension }
