<?php
/**
 * Parkhaus.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ParkhausModule\Form\Type\Finder;

use RK\ParkhausModule\Form\Type\Finder\Base\AbstractVehicleImageFinderType;

/**
 * Vehicle image finder form type implementation class.
 */
class VehicleImageFinderType extends AbstractVehicleImageFinderType
{
    // feel free to extend the base form type class here
}
