services:
    # Form types
    
    rk_websitehelper_module.form.type.linkerquicknav:
        class: RK\WebsiteHelperModule\Form\Type\QuickNavigation\LinkerQuickNavType
        arguments:
            - "@translator.default"
            - "@rk_websitehelper_module.listentries_helper"
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.type.carouselitemquicknav:
        class: RK\WebsiteHelperModule\Form\Type\QuickNavigation\CarouselItemQuickNavType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@rk_websitehelper_module.listentries_helper"
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.type.carouselquicknav:
        class: RK\WebsiteHelperModule\Form\Type\QuickNavigation\CarouselQuickNavType
        arguments:
            - "@translator.default"
            - "@rk_websitehelper_module.listentries_helper"
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.type.websiteimagequicknav:
        class: RK\WebsiteHelperModule\Form\Type\QuickNavigation\WebsiteImageQuickNavType
        arguments:
            - "@translator.default"
            - "@rk_websitehelper_module.listentries_helper"
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.handler.linker:
        class: RK\WebsiteHelperModule\Form\Handler\Linker\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@rk_websitehelper_module.entity_factory"
            - "@rk_websitehelper_module.controller_helper"
            - "@rk_websitehelper_module.model_helper"
            - "@rk_websitehelper_module.selection_helper"
            - "@rk_websitehelper_module.workflow_helper"
            - "@rk_websitehelper_module.hook_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.type.linker:
        class: RK\WebsiteHelperModule\Form\Type\LinkerType
        arguments:
            - "@translator.default"
            - "@rk_websitehelper_module.entity_factory"
            - "@rk_websitehelper_module.listentries_helper"
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.handler.carouselitem:
        class: RK\WebsiteHelperModule\Form\Handler\CarouselItem\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@rk_websitehelper_module.entity_factory"
            - "@rk_websitehelper_module.controller_helper"
            - "@rk_websitehelper_module.model_helper"
            - "@rk_websitehelper_module.selection_helper"
            - "@rk_websitehelper_module.workflow_helper"
            - "@rk_websitehelper_module.hook_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.type.carouselitem:
        class: RK\WebsiteHelperModule\Form\Type\CarouselItemType
        arguments:
            - "@translator.default"
            - "@rk_websitehelper_module.entity_factory"
            - "@rk_websitehelper_module.listentries_helper"
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.handler.carousel:
        class: RK\WebsiteHelperModule\Form\Handler\Carousel\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@rk_websitehelper_module.entity_factory"
            - "@rk_websitehelper_module.controller_helper"
            - "@rk_websitehelper_module.model_helper"
            - "@rk_websitehelper_module.selection_helper"
            - "@rk_websitehelper_module.workflow_helper"
            - "@rk_websitehelper_module.hook_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.type.carousel:
        class: RK\WebsiteHelperModule\Form\Type\CarouselType
        arguments:
            - "@translator.default"
            - "@rk_websitehelper_module.entity_factory"
            - "@rk_websitehelper_module.listentries_helper"
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.handler.websiteimage:
        class: RK\WebsiteHelperModule\Form\Handler\WebsiteImage\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@rk_websitehelper_module.entity_factory"
            - "@rk_websitehelper_module.controller_helper"
            - "@rk_websitehelper_module.model_helper"
            - "@rk_websitehelper_module.selection_helper"
            - "@rk_websitehelper_module.workflow_helper"
            - "@rk_websitehelper_module.hook_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.type.websiteimage:
        class: RK\WebsiteHelperModule\Form\Type\WebsiteImageType
        arguments:
            - "@translator.default"
            - "@rk_websitehelper_module.entity_factory"
            - "@rk_websitehelper_module.listentries_helper"
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.type.deleteentity:
        class: RK\WebsiteHelperModule\Form\DeleteEntityType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.type.block.itemlist:
        class: RK\WebsiteHelperModule\Block\Form\Type\ItemListBlockType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.type.linkerfinder:
        class: RK\WebsiteHelperModule\Form\Type\Finder\LinkerFinderType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.type.carouselitemfinder:
        class: RK\WebsiteHelperModule\Form\Type\Finder\CarouselItemFinderType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.type.carouselfinder:
        class: RK\WebsiteHelperModule\Form\Type\Finder\CarouselFinderType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.type.websiteimagefinder:
        class: RK\WebsiteHelperModule\Form\Type\Finder\WebsiteImageFinderType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    rk_websitehelper_module.form.type.appsettings:
        class: RK\WebsiteHelperModule\Form\AppSettingsType
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
        tags:
            - { name: form.type }
