rkwebsitehelpermodule:
    # define routing support for these controllers
    resource: "@RKWebsiteHelperModule/Controller"
    # enable support for defining routes by annotations
    type: annotation
