services:
    # Twig extension
    rk_websitehelper_module.twig_extension:
        class: RK\WebsiteHelperModule\Twig\TwigExtension
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
            - "@rk_websitehelper_module.workflow_helper"
            - "@rk_websitehelper_module.listentries_helper"
        public: false
        tags:
            - { name: twig.extension }
