<?php
/**
 * ParkHaus.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ParkHausModule\Container\Base;

use Zikula\Bundle\HookBundle\AbstractHookContainer as ZikulaHookContainer;

use Zikula\Bundle\HookBundle\Bundle\SubscriberBundle;

/**
 * Base class for hook container methods.
 */
abstract class AbstractHookContainer extends ZikulaHookContainer
{
    /**
     * Define the hook bundles supported by this module.
     *
     * @return void
     */
    protected function setupHookBundles()
    {
        $bundle = new SubscriberBundle('RKParkHausModule', 'subscriber.rkparkhausmodule.ui_hooks.vehicles', 'ui_hooks', $this->__('rkparkhausmodule. Vehicles Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'rkparkhausmodule.ui_hooks.vehicles.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'rkparkhausmodule.ui_hooks.vehicles.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'rkparkhausmodule.ui_hooks.vehicles.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'rkparkhausmodule.ui_hooks.vehicles.validate_edit');
        // Validate input from an ui delete form.
        $bundle->addEvent('validate_delete', 'rkparkhausmodule.ui_hooks.vehicles.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'rkparkhausmodule.ui_hooks.vehicles.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'rkparkhausmodule.ui_hooks.vehicles.process_delete');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new SubscriberBundle('RKParkHausModule', 'subscriber.rkparkhausmodule.filter_hooks.vehicles', 'filter_hooks', $this->__('rkparkhausmodule. Vehicles Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'rkparkhausmodule.filter_hooks.vehicles.filter');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new SubscriberBundle('RKParkHausModule', 'subscriber.rkparkhausmodule.ui_hooks.vehicleimages', 'ui_hooks', $this->__('rkparkhausmodule. Vehicle images Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'rkparkhausmodule.ui_hooks.vehicleimages.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'rkparkhausmodule.ui_hooks.vehicleimages.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'rkparkhausmodule.ui_hooks.vehicleimages.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'rkparkhausmodule.ui_hooks.vehicleimages.validate_edit');
        // Validate input from an ui delete form.
        $bundle->addEvent('validate_delete', 'rkparkhausmodule.ui_hooks.vehicleimages.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'rkparkhausmodule.ui_hooks.vehicleimages.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'rkparkhausmodule.ui_hooks.vehicleimages.process_delete');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new SubscriberBundle('RKParkHausModule', 'subscriber.rkparkhausmodule.filter_hooks.vehicleimages', 'filter_hooks', $this->__('rkparkhausmodule. Vehicle images Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'rkparkhausmodule.filter_hooks.vehicleimages.filter');
        $this->registerHookSubscriberBundle($bundle);
        
        
        
    }
}
