services:
    # Form field types
    
    rk_parkhaus_module.form.type.field.colour:
        class: RK\ParkHausModule\Form\Type\Field\ColourType
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.field.datetime:
        class: RK\ParkHausModule\Form\Type\Field\DateTimeType
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.field.upload:
        class: RK\ParkHausModule\Form\Type\Field\UploadType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@rk_parkhaus_module.image_helper"
            - "@rk_parkhaus_module.upload_helper"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.field.user:
        class: RK\ParkHausModule\Form\Type\Field\UserType
        arguments:
            - "@zikula_users_module.user_repository"
        tags:
            - { name: form.type }
