services:
    # Form field types
    
    rk_parkhaus_module.form.type.field.colour:
        class: RK\ParkHausModule\Form\Type\Field\ColourType
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.field.upload:
        class: RK\ParkHausModule\Form\Type\Field\UploadType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.field.user:
        class: RK\ParkHausModule\Form\Type\Field\UserType
        tags:
            - { name: form.type }
