services:
    # Form field types
    
    rk_parkhaus_module.form.type.field.colour:
        class: RK\ParkHausModule\Form\Type\Field\ColourType
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.field.upload:
        class: RK\ParkHausModule\Form\Type\Field\UploadType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@rk_parkhaus_module.image_helper"
            - "@rk_parkhaus_module.upload_helper"
        tags:
            - { name: form.type }
