services:
    # Form types
    
    rk_parkhaus_module.form.type.vehiclequicknav:
        class: RK\ParkHausModule\Form\Type\QuickNavigation\VehicleQuickNavType
        arguments:
            - "@translator.default"
            - "@rk_parkhaus_module.listentries_helper"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.vehicleimagequicknav:
        class: RK\ParkHausModule\Form\Type\QuickNavigation\VehicleImageQuickNavType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@rk_parkhaus_module.listentries_helper"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.handler.vehicle:
        class: RK\ParkHausModule\Form\Handler\Vehicle\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@rk_parkhaus_module.entity_factory"
            - "@rk_parkhaus_module.controller_helper"
            - "@rk_parkhaus_module.model_helper"
            - "@rk_parkhaus_module.selection_helper"
            - "@rk_parkhaus_module.workflow_helper"
            - "@rk_parkhaus_module.hook_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.vehicle:
        class: RK\ParkHausModule\Form\Type\VehicleType
        arguments:
            - "@translator.default"
            - "@rk_parkhaus_module.entity_factory"
            - "@rk_parkhaus_module.listentries_helper"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.handler.vehicleimage:
        class: RK\ParkHausModule\Form\Handler\VehicleImage\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@rk_parkhaus_module.entity_factory"
            - "@rk_parkhaus_module.controller_helper"
            - "@rk_parkhaus_module.model_helper"
            - "@rk_parkhaus_module.selection_helper"
            - "@rk_parkhaus_module.workflow_helper"
            - "@rk_parkhaus_module.hook_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.vehicleimage:
        class: RK\ParkHausModule\Form\Type\VehicleImageType
        arguments:
            - "@translator.default"
            - "@rk_parkhaus_module.entity_factory"
            - "@rk_parkhaus_module.listentries_helper"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.deleteentity:
        class: RK\ParkHausModule\Form\DeleteEntityType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.block.itemlist:
        class: RK\ParkHausModule\Block\Form\Type\ItemListBlockType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.vehiclefinder:
        class: RK\ParkHausModule\Form\Type\Finder\VehicleFinderType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.vehicleimagefinder:
        class: RK\ParkHausModule\Form\Type\Finder\VehicleImageFinderType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    rk_parkhaus_module.form.type.appsettings:
        class: RK\ParkHausModule\Form\AppSettingsType
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
        tags:
            - { name: form.type }
