<?php
/**
 * ParkHaus.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ParkHausModule\Entity\Factory;

use RK\ParkHausModule\Entity\Factory\Base\AbstractParkHausFactory;

/**
 * Factory class used to create entities and receive entity repositories.
 *
 * This is the concrete factory class.
 */
class ParkHausFactory extends AbstractParkHausFactory
{
    // feel free to customise the factory
}
