<?php
/**
 * Parkhaus.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ParkhausModule\Form\Handler\VehicleImage;

use RK\ParkhausModule\Form\Handler\VehicleImage\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of the Form called by the rKParkhausModule_vehicleImage_edit() function.
 * It aims on the vehicle image object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
