<?php
/**
 * Sponsoring.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace RK\SponsoringModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use RK\SponsoringModule\Entity\SponsorEntity;

/**
 * Event base class for filtering sponsor processing.
 */
class AbstractFilterSponsorEvent extends Event
{
    /**
     * @var SponsorEntity Reference to treated entity instance.
     */
    protected $sponsor;

    public function __construct(SponsorEntity $sponsor)
    {
        $this->sponsor = $sponsor;
    }

    public function getSponsor()
    {
        return $this->sponsor;
    }
}
