<?php
/**
 * ParkHaus.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ParkHausModule\Entity;

use RK\ParkHausModule\Entity\Base\AbstractVehicleImageEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use UserUtil;
use RK\ParkHausModule\Traits\EntityWorkflowTrait;
use RK\ParkHausModule\Traits\StandardFieldsTrait;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the concrete entity class for vehicle image entities.
 * @ORM\Entity(repositoryClass="\RK\ParkHausModule\Entity\Repository\VehicleImageRepository")
 * @ORM\Table(name="rk_parkha_vehicleimage",
 *     indexes={
 *         @ORM\Index(name="workflowstateindex", columns={"workflowState"})
 *     }
 * )
 */
class VehicleImageEntity extends BaseEntity
{
    // feel free to add your own methods here
}
