services:
    rk_websitehelper_module.link_container:
        class: RK\WebsitehelperModule\Container\LinkContainer
        arguments: ["@translator.default", "@router", "@zikula_permissions_module.api.permission", "@rk_websitehelper_module.controller_helper", "@zikula_users_module.current_user"]
        tags:
            - { name: zikula.link_container }
