<?php
/**
 * Websitehelper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace RK\WebsitehelperModule\DependencyInjection;

use RK\WebsitehelperModule\DependencyInjection\Base\AbstractRKWebsitehelperExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class RKWebsitehelperExtension extends AbstractRKWebsitehelperExtension
{
    // custom enhancements can go here
}
