<?php
/**
 * ParkHaus.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ParkHausModule\Form\Type\Field;

use RK\ParkHausModule\Form\Type\Field\Base\AbstractUserType;

/**
 * User field type implementation class.
 */
class UserType extends AbstractUserType
{
    // feel free to add your customisation here
}
