services:
    # Form field types
    
    rk_download_module.form.type.field.upload:
        class: RK\DownLoadModule\Form\Type\Field\UploadType
        arguments:
            - "@translator.default"
            - "@rk_download_module.image_helper"
        tags:
            - { name: form.type }
