<?php
/**
 * Parkhaus.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ParkhausModule\Entity;

use RK\ParkhausModule\Entity\Base\AbstractVehicleEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;
use DoctrineExtensions\StandardFields\Mapping\Annotation as ZK;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the concrete entity class for vehicle entities.
 * @ORM\Entity(repositoryClass="\RK\ParkhausModule\Entity\Repository\VehicleRepository")
 * @ORM\Table(name="rk_parkha_vehicle",
 *     indexes={
 *         @ORM\Index(name="workflowstateindex", columns={"workflowState"})
 *     }
 * )
 */
class VehicleEntity extends BaseEntity
{
    // feel free to add your own methods here
}
