<?php
/**
 * ParkHaus.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ParkHausModule;

use RK\ParkHausModule\Base\AbstractParkHausModuleInstaller;

/**
 * Installer implementation class.
 */
class ParkHausModuleInstaller extends AbstractParkHausModuleInstaller
{
    // feel free to extend the installer here
	
	    $result = parent::install();

 

    if (true === $result) {

        // eigene Werte setzen
        $this->setVar('enableShrinkingForVehicleTitleImage', true);
        $this->setVar('shrinkWidthVehicleTitleImage', 1800);
        $this->setVar('shrinkHeightVehicleTitleImage', 600);
        $this->setVar('enableShrinkingForVehicleVehicleImage', true);
        $this->setVar('shrinkWidthVehicleVehicleImage', 800);
        $this->setVar('shrinkHeightVehicleVehicleImage', 600);
        $this->setVar('enableShrinkingForVehicleImageVehicleImage', true);
        $this->setVar('shrinkWidthVehicleImageVehicleImage', 800);
        $this->setVar('shrinkHeightVehicleImageVehicleImage', 600);

    }

 

    return $result;
	
}
