<?php
/**
 * Parkhaus.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ParkhausModule\Base;

/**
 * Events definition base class.
 */
abstract class AbstractParkhausEvents
{
    /**
     * The rkparkhausmodule.vehicle_post_load event is thrown when vehicles
     * are loaded from the database.
     *
     * The event listener receives an
     * RK\ParkhausModule\Event\FilterVehicleEvent instance.
     *
     * @see RK\ParkhausModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const VEHICLE_POST_LOAD = 'rkparkhausmodule.vehicle_post_load';
    
    /**
     * The rkparkhausmodule.vehicle_pre_persist event is thrown before a new vehicle
     * is created in the system.
     *
     * The event listener receives an
     * RK\ParkhausModule\Event\FilterVehicleEvent instance.
     *
     * @see RK\ParkhausModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const VEHICLE_PRE_PERSIST = 'rkparkhausmodule.vehicle_pre_persist';
    
    /**
     * The rkparkhausmodule.vehicle_post_persist event is thrown after a new vehicle
     * has been created in the system.
     *
     * The event listener receives an
     * RK\ParkhausModule\Event\FilterVehicleEvent instance.
     *
     * @see RK\ParkhausModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const VEHICLE_POST_PERSIST = 'rkparkhausmodule.vehicle_post_persist';
    
    /**
     * The rkparkhausmodule.vehicle_pre_remove event is thrown before an existing vehicle
     * is removed from the system.
     *
     * The event listener receives an
     * RK\ParkhausModule\Event\FilterVehicleEvent instance.
     *
     * @see RK\ParkhausModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const VEHICLE_PRE_REMOVE = 'rkparkhausmodule.vehicle_pre_remove';
    
    /**
     * The rkparkhausmodule.vehicle_post_remove event is thrown after an existing vehicle
     * has been removed from the system.
     *
     * The event listener receives an
     * RK\ParkhausModule\Event\FilterVehicleEvent instance.
     *
     * @see RK\ParkhausModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const VEHICLE_POST_REMOVE = 'rkparkhausmodule.vehicle_post_remove';
    
    /**
     * The rkparkhausmodule.vehicle_pre_update event is thrown before an existing vehicle
     * is updated in the system.
     *
     * The event listener receives an
     * RK\ParkhausModule\Event\FilterVehicleEvent instance.
     *
     * @see RK\ParkhausModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const VEHICLE_PRE_UPDATE = 'rkparkhausmodule.vehicle_pre_update';
    
    /**
     * The rkparkhausmodule.vehicle_post_update event is thrown after an existing new vehicle
     * has been updated in the system.
     *
     * The event listener receives an
     * RK\ParkhausModule\Event\FilterVehicleEvent instance.
     *
     * @see RK\ParkhausModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const VEHICLE_POST_UPDATE = 'rkparkhausmodule.vehicle_post_update';
    
    /**
     * The rkparkhausmodule.vehicleimage_post_load event is thrown when vehicle images
     * are loaded from the database.
     *
     * The event listener receives an
     * RK\ParkhausModule\Event\FilterVehicleImageEvent instance.
     *
     * @see RK\ParkhausModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const VEHICLEIMAGE_POST_LOAD = 'rkparkhausmodule.vehicleimage_post_load';
    
    /**
     * The rkparkhausmodule.vehicleimage_pre_persist event is thrown before a new vehicle image
     * is created in the system.
     *
     * The event listener receives an
     * RK\ParkhausModule\Event\FilterVehicleImageEvent instance.
     *
     * @see RK\ParkhausModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const VEHICLEIMAGE_PRE_PERSIST = 'rkparkhausmodule.vehicleimage_pre_persist';
    
    /**
     * The rkparkhausmodule.vehicleimage_post_persist event is thrown after a new vehicle image
     * has been created in the system.
     *
     * The event listener receives an
     * RK\ParkhausModule\Event\FilterVehicleImageEvent instance.
     *
     * @see RK\ParkhausModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const VEHICLEIMAGE_POST_PERSIST = 'rkparkhausmodule.vehicleimage_post_persist';
    
    /**
     * The rkparkhausmodule.vehicleimage_pre_remove event is thrown before an existing vehicle image
     * is removed from the system.
     *
     * The event listener receives an
     * RK\ParkhausModule\Event\FilterVehicleImageEvent instance.
     *
     * @see RK\ParkhausModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const VEHICLEIMAGE_PRE_REMOVE = 'rkparkhausmodule.vehicleimage_pre_remove';
    
    /**
     * The rkparkhausmodule.vehicleimage_post_remove event is thrown after an existing vehicle image
     * has been removed from the system.
     *
     * The event listener receives an
     * RK\ParkhausModule\Event\FilterVehicleImageEvent instance.
     *
     * @see RK\ParkhausModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const VEHICLEIMAGE_POST_REMOVE = 'rkparkhausmodule.vehicleimage_post_remove';
    
    /**
     * The rkparkhausmodule.vehicleimage_pre_update event is thrown before an existing vehicle image
     * is updated in the system.
     *
     * The event listener receives an
     * RK\ParkhausModule\Event\FilterVehicleImageEvent instance.
     *
     * @see RK\ParkhausModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const VEHICLEIMAGE_PRE_UPDATE = 'rkparkhausmodule.vehicleimage_pre_update';
    
    /**
     * The rkparkhausmodule.vehicleimage_post_update event is thrown after an existing new vehicle image
     * has been updated in the system.
     *
     * The event listener receives an
     * RK\ParkhausModule\Event\FilterVehicleImageEvent instance.
     *
     * @see RK\ParkhausModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const VEHICLEIMAGE_POST_UPDATE = 'rkparkhausmodule.vehicleimage_post_update';
    
}
