<?php
/**
 * Websitehelper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace RK\WebsitehelperModule\Form\Handler\Linker;

use RK\WebsitehelperModule\Form\Handler\Linker\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of the Form called by the rKWebsitehelperModule_linker_edit() function.
 * It aims on the linker object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
