<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace RK\TeamModule\Entity\Factory;

use RK\TeamModule\Entity\Factory\Base\AbstractPersonFactory;

/**
 * Factory class used to retrieve entity and repository instances.
 *
 * This is the concrete factory class for person entities.
 */
class PersonFactory extends AbstractPersonFactory
{
    // feel free to customise the manager
}
