<?php
/**
 * WebsiteHelper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\WebsiteHelperModule\Entity\Factory;

use RK\WebsiteHelperModule\Entity\Factory\Base\AbstractWebsiteImageFactory;

/**
 * Factory class used to retrieve entity and repository instances.
 *
 * This is the concrete factory class for website image entities.
 */
class WebsiteImageFactory extends AbstractWebsiteImageFactory
{
    // feel free to customise the manager
}
