<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace RK\TeamModule\Menu;

use RK\TeamModule\Menu\Base\AbstractItemActionsMenu;

/**
 * This is the item actions menu implementation class.
 */
class ItemActionsMenu extends AbstractItemActionsMenu
{
    // feel free to add own extensions here
}
