<?php
/**
 * Sponsoring.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace RK\SponsoringModule\Helper;

use RK\SponsoringModule\Helper\Base\AbstractSearchHelper;

/**
 * Search helper implementation class.
 */
class SearchHelper extends AbstractSearchHelper
{
    // feel free to extend the search helper here
}
