<?php
/**
 * Sponsoring.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace RK\SponsoringModule;

use RK\SponsoringModule\Base\AbstractSponsoringModuleInstaller;

/**
 * Installer implementation class.
 */
class SponsoringModuleInstaller extends AbstractSponsoringModuleInstaller
{
    // feel free to extend the installer here
	
    if (true === $result) {

        // eigene Werte setzen
        $this->setVar('enableShrinkingForSponsorLogo', true);
        $this->setVar('shrinkWidthSponsorLogo', 1200);
        $this->setVar('shrinkHeightSponsorLogo', 900);

    }

 

    return $result;

}
