<?php
/**
 * WebsiteHelper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\WebsiteHelperModule\Helper;

use RK\WebsiteHelperModule\Helper\Base\AbstractViewHelper;

/**
 * Helper implementation class for view layer methods.
 */
class ViewHelper extends AbstractViewHelper
{
    // feel free to add your own convenience methods here
}
