<?php
/**
 * ParkHaus.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ParkHausModule;

use RK\ParkHausModule\Base\AbstractUploadHandler;

/**
 * Upload handler implementation class.
 */
class UploadHandler extends AbstractUploadHandler
{
    // feel free to add your upload handler enhancements here
}
