<?php
/**
 * Sponsoring.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\SponsoringModule\Form\Handler\Sponsor;

use RK\SponsoringModule\Form\Handler\Sponsor\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of the Form called by the rKSponsoringModule_sponsor_edit() function.
 * It aims on the sponsor object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
