services:
    # Upload handler class
    rk_sponsoring_module.upload_handler:
        class: RK\SponsoringModule\UploadHandler
        arguments: ["@translator.default", "@zikula_users_module.current_user", "@zikula_extensions_module.api.variable"]
