<?php
/**
 * Sponsoring.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\SponsoringModule\Base;

/**
 * Events definition base class.
 */
abstract class AbstractSponsoringEvents
{
    /**
     * The rksponsoringmodule.sponsor_post_load event is thrown when sponsors
     * are loaded from the database.
     *
     * The event listener receives an
     * RK\SponsoringModule\Event\FilterSponsorEvent instance.
     *
     * @see RK\SponsoringModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const SPONSOR_POST_LOAD = 'rksponsoringmodule.sponsor_post_load';
    
    /**
     * The rksponsoringmodule.sponsor_pre_persist event is thrown before a new sponsor
     * is created in the system.
     *
     * The event listener receives an
     * RK\SponsoringModule\Event\FilterSponsorEvent instance.
     *
     * @see RK\SponsoringModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const SPONSOR_PRE_PERSIST = 'rksponsoringmodule.sponsor_pre_persist';
    
    /**
     * The rksponsoringmodule.sponsor_post_persist event is thrown after a new sponsor
     * has been created in the system.
     *
     * The event listener receives an
     * RK\SponsoringModule\Event\FilterSponsorEvent instance.
     *
     * @see RK\SponsoringModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const SPONSOR_POST_PERSIST = 'rksponsoringmodule.sponsor_post_persist';
    
    /**
     * The rksponsoringmodule.sponsor_pre_remove event is thrown before an existing sponsor
     * is removed from the system.
     *
     * The event listener receives an
     * RK\SponsoringModule\Event\FilterSponsorEvent instance.
     *
     * @see RK\SponsoringModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const SPONSOR_PRE_REMOVE = 'rksponsoringmodule.sponsor_pre_remove';
    
    /**
     * The rksponsoringmodule.sponsor_post_remove event is thrown after an existing sponsor
     * has been removed from the system.
     *
     * The event listener receives an
     * RK\SponsoringModule\Event\FilterSponsorEvent instance.
     *
     * @see RK\SponsoringModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const SPONSOR_POST_REMOVE = 'rksponsoringmodule.sponsor_post_remove';
    
    /**
     * The rksponsoringmodule.sponsor_pre_update event is thrown before an existing sponsor
     * is updated in the system.
     *
     * The event listener receives an
     * RK\SponsoringModule\Event\FilterSponsorEvent instance.
     *
     * @see RK\SponsoringModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const SPONSOR_PRE_UPDATE = 'rksponsoringmodule.sponsor_pre_update';
    
    /**
     * The rksponsoringmodule.sponsor_post_update event is thrown after an existing new sponsor
     * has been updated in the system.
     *
     * The event listener receives an
     * RK\SponsoringModule\Event\FilterSponsorEvent instance.
     *
     * @see RK\SponsoringModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const SPONSOR_POST_UPDATE = 'rksponsoringmodule.sponsor_post_update';
    
}
