services:
    # Entity factory classes
    rk_websitehelper_module.linker_factory:
        class: RK\WebsiteHelperModule\Entity\Factory\LinkerFactory
        arguments: ["@doctrine.orm.entity_manager", RK\WebsiteHelperModule\Entity\LinkerEntity]
    
    rk_websitehelper_module.carouselItem_factory:
        class: RK\WebsiteHelperModule\Entity\Factory\CarouselItemFactory
        arguments: ["@doctrine.orm.entity_manager", RK\WebsiteHelperModule\Entity\CarouselItemEntity]
    
    rk_websitehelper_module.carousel_factory:
        class: RK\WebsiteHelperModule\Entity\Factory\CarouselFactory
        arguments: ["@doctrine.orm.entity_manager", RK\WebsiteHelperModule\Entity\CarouselEntity]
    
    rk_websitehelper_module.websiteImage_factory:
        class: RK\WebsiteHelperModule\Entity\Factory\WebsiteImageFactory
        arguments: ["@doctrine.orm.entity_manager", RK\WebsiteHelperModule\Entity\WebsiteImageEntity]
    
