services:
    # Event subscriber and listener classes
    rk_websitehelper_module.entity_lifecycle_listener:
        class: RK\WebsitehelperModule\Listener\EntityLifecycleListener
        tags:
            - { name: doctrine.event_subscriber }
    
    rk_websitehelper_module.core_listener:
        class: RK\WebsitehelperModule\Listener\CoreListener
        tags:
            - { name: kernel.event_subscriber }
    
    rk_websitehelper_module.kernel_listener:
        class: RK\WebsitehelperModule\Listener\KernelListener
        tags:
            - { name: kernel.event_subscriber }
    
    rk_websitehelper_module.installer_listener:
        class: RK\WebsitehelperModule\Listener\InstallerListener
        tags:
            - { name: kernel.event_subscriber }
    
    rk_websitehelper_module.moduledispatch_listener:
        class: RK\WebsitehelperModule\Listener\ModuleDispatchListener
        tags:
            - { name: kernel.event_subscriber }
    
    rk_websitehelper_module.mailer_listener:
        class: RK\WebsitehelperModule\Listener\MailerListener
        tags:
            - { name: kernel.event_subscriber }
    
    rk_websitehelper_module.page_listener:
        class: RK\WebsitehelperModule\Listener\PageListener
        tags:
            - { name: kernel.event_subscriber }
    
    rk_websitehelper_module.theme_listener:
        class: RK\WebsitehelperModule\Listener\ThemeListener
        tags:
            - { name: kernel.event_subscriber }
    
    rk_websitehelper_module.view_listener:
        class: RK\WebsitehelperModule\Listener\ViewListener
        tags:
            - { name: kernel.event_subscriber }
    
    rk_websitehelper_module.userlogin_listener:
        class: RK\WebsitehelperModule\Listener\UserLoginListener
        tags:
            - { name: kernel.event_subscriber }
    
    rk_websitehelper_module.userlogout_listener:
        class: RK\WebsitehelperModule\Listener\UserLogoutListener
        tags:
            - { name: kernel.event_subscriber }
    
    rk_websitehelper_module.user_listener:
        class: RK\WebsitehelperModule\Listener\UserListener
        tags:
            - { name: kernel.event_subscriber }
    
    rk_websitehelper_module.userregistration_listener:
        class: RK\WebsitehelperModule\Listener\UserRegistrationListener
        tags:
            - { name: kernel.event_subscriber }
    
    rk_websitehelper_module.users_listener:
        class: RK\WebsitehelperModule\Listener\UsersListener
        tags:
            - { name: kernel.event_subscriber }
    
    rk_websitehelper_module.group_listener:
        class: RK\WebsitehelperModule\Listener\GroupListener
        tags:
            - { name: kernel.event_subscriber }
    
    rk_websitehelper_module.thirdparty_listener:
        class: RK\WebsitehelperModule\Listener\ThirdPartyListener
        tags:
            - { name: kernel.event_subscriber }
    
