<?php
/**
 * ParkHaus.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ParkHausModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use RK\ParkHausModule\Entity\VehicleEntity;

/**
 * Event base class for filtering vehicle processing.
 */
class AbstractFilterVehicleEvent extends Event
{
    /**
     * @var VehicleEntity Reference to treated entity instance.
     */
    protected $vehicle;

    public function __construct(VehicleEntity $vehicle)
    {
        $this->vehicle = $vehicle;
    }

    public function getVehicle()
    {
        return $this->vehicle;
    }
}
