services:
    # Form field types
    
    rk_team_module.form.type.field.upload:
        class: RK\TeamModule\Form\Type\Field\UploadType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }
    
    rk_team_module.form.type.field.user:
        class: RK\TeamModule\Form\Type\Field\UserType
        tags:
            - { name: form.type }
