<?php
/**
 * Parkhaus.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ParkhausModule\Entity\Factory;

use RK\ParkhausModule\Entity\Factory\Base\AbstractVehicleFactory;

/**
 * Factory class used to retrieve entity and repository instances.
 *
 * This is the concrete factory class for vehicle entities.
 */
class VehicleFactory extends AbstractVehicleFactory
{
    // feel free to customise the manager
}
