<?php
/**
 * Download.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace RK\DownloadModule\Form\Type;

use RK\DownloadModule\Form\Type\Base\AbstractFileType;

/**
 * File editing form type implementation class.
 */
class FileType extends AbstractFileType
{
    // feel free to extend the file editing form type class here
}
