<?php
/**
 * Websitehelper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace RK\WebsitehelperModule\Event;

use RK\WebsitehelperModule\Event\Base\AbstractFilterCarouselItemEvent;

/**
 * Event implementation class for filtering carousel item processing.
 */
class FilterCarouselItemEvent extends AbstractFilterCarouselItemEvent
{
    // feel free to extend the event class here
}
