<?php
/**
 * Sponsoring.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace RK\SponsoringModule\Entity;

use RK\SponsoringModule\Entity\Base\AbstractSponsorEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use DoctrineExtensions\StandardFields\Mapping\Annotation as ZK;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the concrete entity class for sponsor entities.
 * @ORM\Entity(repositoryClass="\RK\SponsoringModule\Entity\Repository\SponsorRepository")
 * @ORM\Table(name="rk_sponso_sponsor",
 *     indexes={
 *         @ORM\Index(name="workflowstateindex", columns={"workflowState"})
 *     }
 * )
 */
class SponsorEntity extends BaseEntity
{
    // feel free to add your own methods here
}
