<?php
/**
 * Sponsoring.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace RK\SponsoringModule\Form\Type\QuickNavigation;

use RK\SponsoringModule\Form\Type\QuickNavigation\Base\AbstractSponsorQuickNavType;

/**
 * Sponsor quick navigation form type implementation class.
 */
class SponsorQuickNavType extends AbstractSponsorQuickNavType
{
    // feel free to extend the base form type class here
}
