<?php
/**
 * Websitehelper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace RK\WebsitehelperModule\Container;

use RK\WebsitehelperModule\Container\Base\AbstractHookContainer;

/**
 * Implementation class for hook container methods.
 */
class HookContainer extends AbstractHookContainer
{
    // feel free to add your own convenience methods here
}
