<?php
/**
 * WebsiteHelper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\WebsiteHelperModule\Form\Type\QuickNavigation;

use RK\WebsiteHelperModule\Form\Type\QuickNavigation\Base\AbstractWebsiteImageQuickNavType;

/**
 * Website image quick navigation form type implementation class.
 */
class WebsiteImageQuickNavType extends AbstractWebsiteImageQuickNavType
{
    // feel free to extend the base form type class here
}
