<?php
/**
 * WebsiteHelper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\WebsiteHelperModule\Form\Type;

use RK\WebsiteHelperModule\Form\Type\Base\AbstractCarouselType;

/**
 * Carousel editing form type implementation class.
 */
class CarouselType extends AbstractCarouselType
{
    // feel free to extend the carousel editing form type class here
}
