<?php
/**
 * Websitehelper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace RK\WebsitehelperModule\Form\Type\QuickNavigation;

use RK\WebsitehelperModule\Form\Type\QuickNavigation\Base\AbstractLinkerQuickNavType;

/**
 * Linker quick navigation form type implementation class.
 */
class LinkerQuickNavType extends AbstractLinkerQuickNavType
{
    // feel free to extend the base form type class here
}
