<?php
/**
 * WebsiteHelper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\WebsiteHelperModule\Form\Handler\WebsiteImage;

use RK\WebsiteHelperModule\Form\Handler\WebsiteImage\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of the Form called by the rKWebsiteHelperModule_websiteImage_edit() function.
 * It aims on the website image object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
