<?php
/**
 * ParkHaus.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ParkHausModule\Base;

use Doctrine\DBAL\Connection;
use EventUtil;
use RuntimeException;
use UserUtil;
use Zikula\Core\AbstractExtensionInstaller;
use Zikula_Workflow_Util;

/**
 * Installer base class.
 */
abstract class AbstractParkHausModuleInstaller extends AbstractExtensionInstaller
{
    /**
     * Install the RKParkHausModule application.
     *
     * @return boolean True on success, or false
     *
     * @throws RuntimeException Thrown if database tables can not be created or another error occurs
     */
    public function install()
    {
        $logger = $this->container->get('logger');
    
        // Check if upload directories exist and if needed create them
        try {
            $container = $this->container;
            $controllerHelper = new \RK\ParkHausModule\Helper\ControllerHelper($container, $container->get('translator.default'), $container->get('session'), $container->get('logger'));
            $controllerHelper->checkAndCreateAllUploadFolders();
        } catch (\Exception $e) {
            $this->addFlash('error', $e->getMessage());
            $logger->error('{app}: User {user} could not create upload folders during installation. Error details: {errorMessage}.', ['app' => 'RKParkHausModule', 'user' => $userName, 'errorMessage' => $e->getMessage()]);
        
            return false;
        }
        // create all tables from according entity definitions
        try {
            $this->schemaTool->create($this->listEntityClasses());
        } catch (\Exception $e) {
            $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $e->getMessage());
            $logger->error('{app}: Could not create the database tables during installation. Error details: {errorMessage}.', ['app' => 'RKParkHausModule', 'errorMessage' => $e->getMessage()]);
    
            return false;
        }
    
        // set up all our vars with initial values
        $this->setVar('myDirectory', '');
        $this->setVar('myText', '');
        $this->setVar('vehicleEntriesPerPage', 10);
        $this->setVar('vehicleImageEntriesPerPage', 10);
        $this->setVar('enableShrinkingForVehicleTitleImage', false);
        $this->setVar('shrinkWidthVehicleTitleImage', 800);
        $this->setVar('shrinkHeightVehicleTitleImage', 600);
        $this->setVar('enableShrinkingForVehicleVehicleImage', false);
        $this->setVar('shrinkWidthVehicleVehicleImage', 800);
        $this->setVar('shrinkHeightVehicleVehicleImage', 600);
        $this->setVar('enableShrinkingForVehicleImageVehicleImage', false);
        $this->setVar('shrinkWidthVehicleImageVehicleImage', 800);
        $this->setVar('shrinkHeightVehicleImageVehicleImage', 600);
        $this->setVar('thumbnailModeVehicle',  'inset' );
        $this->setVar('thumbnailWidthVehicleTitleImageView', 32);
        $this->setVar('thumbnailHeightVehicleTitleImageView', 24);
        $this->setVar('thumbnailWidthVehicleTitleImageDisplay', 240);
        $this->setVar('thumbnailHeightVehicleTitleImageDisplay', 180);
        $this->setVar('thumbnailWidthVehicleTitleImageEdit', 240);
        $this->setVar('thumbnailHeightVehicleTitleImageEdit', 180);
        $this->setVar('thumbnailWidthVehicleVehicleImageView', 32);
        $this->setVar('thumbnailHeightVehicleVehicleImageView', 24);
        $this->setVar('thumbnailWidthVehicleVehicleImageDisplay', 240);
        $this->setVar('thumbnailHeightVehicleVehicleImageDisplay', 180);
        $this->setVar('thumbnailWidthVehicleVehicleImageEdit', 240);
        $this->setVar('thumbnailHeightVehicleVehicleImageEdit', 180);
        $this->setVar('thumbnailModeVehicleImage',  'inset' );
        $this->setVar('thumbnailWidthVehicleImageVehicleImageView', 32);
        $this->setVar('thumbnailHeightVehicleImageVehicleImageView', 24);
        $this->setVar('thumbnailWidthVehicleImageVehicleImageDisplay', 240);
        $this->setVar('thumbnailHeightVehicleImageVehicleImageDisplay', 180);
        $this->setVar('thumbnailWidthVehicleImageVehicleImageEdit', 240);
        $this->setVar('thumbnailHeightVehicleImageVehicleImageEdit', 180);
    
        // create the default data
        $this->createDefaultData();
    
        // install subscriber hooks
        $this->hookApi->installSubscriberHooks($this->bundle->getMetaData());
        
    
        // initialisation successful
        return true;
    }
    
    /**
     * Upgrade the RKParkHausModule application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldVersion Version to upgrade from
     *
     * @return boolean True on success, false otherwise
     *
     * @throws RuntimeException Thrown if database tables can not be updated
     */
    public function upgrade($oldVersion)
    {
    /*
        $logger = $this->container->get('logger');
    
        // Upgrade dependent on old version number
        switch ($oldVersion) {
            case '1.0.0':
                // do something
                // ...
                // update the database schema
                try {
                    $this->schemaTool->update($this->listEntityClasses());
                } catch (\Exception $e) {
                    $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $e->getMessage());
                    $logger->error('{app}: Could not update the database tables during the upgrade. Error details: {errorMessage}.', ['app' => 'RKParkHausModule', 'errorMessage' => $e->getMessage()]);
    
                    return false;
                }
        }
    
        // Note there are several helpers available for making migrating your extension from Zikula 1.3 to 1.4 easier.
        // The following convenience methods are each responsible for a single aspect of upgrading to Zikula 1.4.x.
    
        // here is a possible usage example
        // of course 1.2.3 should match the number you used for the last stable 1.3.x module version.
        /* if ($oldVersion = '1.2.3') {
            // rename module for all modvars
            $this->updateModVarsTo14();
            
            // update extension information about this app
            $this->updateExtensionInfoFor14();
            
            // rename existing permission rules
            $this->renamePermissionsFor14();
            
            // rename all tables
            $this->renameTablesFor14();
            
            // remove event handler definitions from database
            $this->dropEventHandlersFromDatabase();
            
            // update module name in the hook tables
            $this->updateHookNamesFor14();
            
            // update module name in the workflows table
            $this->updateWorkflowsFor14();
        } * /
    */
    
        // update successful
        return true;
    }
    
    /**
     * Renames the module name for variables in the module_vars table.
     */
    protected function updateModVarsTo14()
    {
        $dbName = $this->getDbName();
        $conn = $this->getConnection();
    
        $conn->executeQuery("
            UPDATE $dbName.module_vars
            SET modname = 'RKParkHausModule'
            WHERE modname = 'ParkHaus';
        ");
    }
    
    /**
     * Renames this application in the core's extensions table.
     */
    protected function updateExtensionInfoFor14()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $conn->executeQuery("
            UPDATE $dbName.modules
            SET name = 'RKParkHausModule',
                directory = 'RK/ParkHausModule'
            WHERE name = 'ParkHaus';
        ");
    }
    
    /**
     * Renames all permission rules stored for this app.
     */
    protected function renamePermissionsFor14()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $componentLength = strlen('ParkHaus') + 1;
    
        $conn->executeQuery("
            UPDATE $dbName.group_perms
            SET component = CONCAT('RKParkHausModule', SUBSTRING(component, $componentLength))
            WHERE component LIKE 'ParkHaus%';
        ");
    }
    
    /**
     * Renames all (existing) tables of this app.
     */
    protected function renameTablesFor14()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $oldPrefix = 'parkha_';
        $oldPrefixLength = strlen($oldPrefix);
        $newPrefix = 'rk_parkha_';
    
        $sm = $conn->getSchemaManager();
        $tables = $sm->listTables();
        foreach ($tables as $table) {
            $tableName = $table->getName();
            if (substr($tableName, 0, $oldPrefixLength) != $oldPrefix) {
                continue;
            }
    
            $newTableName = str_replace($oldPrefix, $newPrefix, $tableName);
    
            $conn->executeQuery("
                RENAME TABLE $dbName.$tableName
                TO $dbName.$newTableName;
            ");
        }
    }
    
    /**
     * Removes event handlers from database as they are now described by service definitions and managed by dependency injection.
     */
    protected function dropEventHandlersFromDatabase()
    {
        EventUtil::unregisterPersistentModuleHandlers('ParkHaus');
    }
    
    /**
     * Updates the module name in the hook tables.
     */
    protected function updateHookNamesFor14()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $conn->executeQuery("
            UPDATE $dbName.hook_area
            SET owner = 'RKParkHausModule'
            WHERE owner = 'ParkHaus';
        ");
    
        $componentLength = strlen('subscriber.parkhaus') + 1;
        $conn->executeQuery("
            UPDATE $dbName.hook_area
            SET areaname = CONCAT('subscriber.rkparkhausmodule', SUBSTRING(areaname, $componentLength))
            WHERE areaname LIKE 'subscriber.parkhaus%';
        ");
    
        $conn->executeQuery("
            UPDATE $dbName.hook_binding
            SET sowner = 'RKParkHausModule'
            WHERE sowner = 'ParkHaus';
        ");
    
        $conn->executeQuery("
            UPDATE $dbName.hook_runtime
            SET sowner = 'RKParkHausModule'
            WHERE sowner = 'ParkHaus';
        ");
    
        $componentLength = strlen('parkhaus') + 1;
        $conn->executeQuery("
            UPDATE $dbName.hook_runtime
            SET eventname = CONCAT('rkparkhausmodule', SUBSTRING(eventname, $componentLength))
            WHERE eventname LIKE 'parkhaus%';
        ");
    
        $conn->executeQuery("
            UPDATE $dbName.hook_subscriber
            SET owner = 'RKParkHausModule'
            WHERE owner = 'ParkHaus';
        ");
    
        $componentLength = strlen('parkhaus') + 1;
        $conn->executeQuery("
            UPDATE $dbName.hook_subscriber
            SET eventname = CONCAT('rkparkhausmodule', SUBSTRING(eventname, $componentLength))
            WHERE eventname LIKE 'parkhaus%';
        ");
    }
    
    /**
     * Updates the module name in the workflows table.
     */
    protected function updateWorkflowsFor14()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $conn->executeQuery("
            UPDATE $dbName.workflows
            SET module = 'RKParkHausModule'
            WHERE module = 'ParkHaus';
        ");
    }
    
    /**
     * Returns connection to the database.
     *
     * @return Connection the current connection
     */
    protected function getConnection()
    {
        $entityManager = $this->container->get('doctrine.orm.default_entity_manager');
        $connection = $entityManager->getConnection();
    
        return $connection;
    }
    
    /**
     * Returns the name of the default system database.
     *
     * @return string the database name
     */
    protected function getDbName()
    {
        return $this->container->getParameter('database_name');
    }
    
    /**
     * Uninstall RKParkHausModule.
     *
     * @return boolean True on success, false otherwise
     *
     * @throws RuntimeException Thrown if database tables or stored workflows can not be removed
     */
    public function uninstall()
    {
        $logger = $this->container->get('logger');
    
        // delete stored object workflows
        $result = Zikula_Workflow_Util::deleteWorkflowsForModule('RKParkHausModule');
        if (false === $result) {
            $this->addFlash('error', $this->__f('An error was encountered while removing stored object workflows for the %s extension.', ['%s' => 'RKParkHausModule']));
            $logger->error('{app}: Could not remove stored object workflows during uninstallation.', ['app' => 'RKParkHausModule']);
    
            return false;
        }
    
        try {
            $this->schemaTool->drop($this->listEntityClasses());
        } catch (\Exception $e) {
            $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $e->getMessage());
            $logger->error('{app}: Could not remove the database tables during uninstallation. Error details: {errorMessage}.', ['app' => 'RKParkHausModule', 'errorMessage' => $e->getMessage()]);
    
            return false;
        }
    
        // uninstall subscriber hooks
        $this->hookApi->uninstallSubscriberHooks($this->bundle->getMetaData());
        
    
        // remove all module vars
        $this->delVars();
    
        // remove all thumbnails
        $manager = $this->container->get('systemplugin.imagine.manager');
        $manager->setModule('RKParkHausModule');
        $manager->cleanupModuleThumbs();
    
        // remind user about upload folders not being deleted
        $uploadPath = $this->container->getParameter('datadir') . '/RKParkHausModule/';
        $this->addFlash('status', $this->__f('The upload directories at [%s] can be removed manually.', ['%s' => $uploadPath]));
    
        // uninstallation successful
        return true;
    }
    
    /**
     * Build array with all entity classes for RKParkHausModule.
     *
     * @return array list of class names
     */
    protected function listEntityClasses()
    {
        $classNames = [];
        $classNames[] = 'RK\ParkHausModule\Entity\VehicleEntity';
        $classNames[] = 'RK\ParkHausModule\Entity\VehicleImageEntity';
    
        return $classNames;
    }
    
    /**
     * Create the default data for RKParkHausModule.
     *
     * @return void
     */
    protected function createDefaultData()
    {
        $entityManager = $this->container->get('doctrine.orm.default_entity_manager');
        $logger = $this->container->get('logger');
        $request = $this->container->get('request_stack')->getMasterRequest();
        
        $entityClass = 'RK\ParkHausModule\Entity\VehicleEntity';
        $entityManager->getRepository($entityClass)->truncateTable($logger);
        $entityClass = 'RK\ParkHausModule\Entity\VehicleImageEntity';
        $entityManager->getRepository($entityClass)->truncateTable($logger);
    }
}
