<?php
/**
 * Sponsoring.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\SponsoringModule\DependencyInjection;

use RK\SponsoringModule\DependencyInjection\Base\AbstractRKSponsoringExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class RKSponsoringExtension extends AbstractRKSponsoringExtension
{
    // custom enhancements can go here
}
