<?php
/**
 * WebsiteHelper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\WebsiteHelperModule\Form\Base;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use Zikula\ExtensionsModule\Api\VariableApi;

/**
 * Configuration form type base class.
 */
abstract class AbstractAppSettingsType extends AbstractType
{
    use TranslatorTrait;

    /**
     * @var VariableApi
     */
    protected $variableApi;

    /**
     * @var array
     */
    protected $modVars;

    /**
     * AppSettingsType constructor.
     *
     * @param TranslatorInterface $translator  Translator service instance
     * @param VariableApi         $variableApi VariableApi service instance
     */
    public function __construct(TranslatorInterface $translator, VariableApi $variableApi)
    {
        $this->setTranslator($translator);
        $this->variableApi = $variableApi;
        $this->modVars = $this->variableApi->getAll('RKWebsiteHelperModule');
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this->addImagesFields($builder, $options);

        $builder
            ->add('save', 'Symfony\Component\Form\Extension\Core\Type\SubmitType', [
                'label' => $this->__('Update configuration'),
                'icon' => 'fa-check',
                'attr' => [
                    'class' => 'btn btn-success'
                ]
            ])
            ->add('cancel', 'Symfony\Component\Form\Extension\Core\Type\SubmitType', [
                'label' => $this->__('Cancel'),
                'icon' => 'fa-times',
                'attr' => [
                    'class' => 'btn btn-default',
                    'formnovalidate' => 'formnovalidate'
                ]
            ])
        ;
    }

    /**
     * Adds fields for images fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addImagesFields(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('enableShrinkingForLinkerLinkerImage', 'Symfony\Component\Form\Extension\Core\Type\CheckboxType', [
                'label' => $this->__('Enable shrinking for linker linker image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Whether to enable shrinking huge images to maximum dimensions. Stores downscaled version of the original image.')
                ],
                'help' => $this->__('Whether to enable shrinking huge images to maximum dimensions. Stores downscaled version of the original image.'),
                'required' => false,
                'data' => (bool)$this->modVars['enableShrinkingForLinkerLinkerImage'],
                'attr' => [
                    'title' => $this->__('The enable shrinking for linker linker image option.'),
                    'class' => 'shrink-enabler'
                ],
            ])
            ->add('shrinkWidthLinkerLinkerImage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Shrink width linker linker image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The maximum image width in pixels.')
                ],
                'help' => $this->__('The maximum image width in pixels.'),
                'required' => false,
                'data' => $this->modVars['shrinkWidthLinkerLinkerImage'],
                'empty_data' => intval('800'),
                'attr' => [
                    'title' => $this->__('Enter the shrink width linker linker image. Only digits are allowed.'),
                    'class' => 'shrinkdimension-shrinkwidthlinkerlinkerimage'
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('shrinkHeightLinkerLinkerImage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Shrink height linker linker image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The maximum image height in pixels.')
                ],
                'help' => $this->__('The maximum image height in pixels.'),
                'required' => false,
                'data' => $this->modVars['shrinkHeightLinkerLinkerImage'],
                'empty_data' => intval('600'),
                'attr' => [
                    'title' => $this->__('Enter the shrink height linker linker image. Only digits are allowed.'),
                    'class' => 'shrinkdimension-shrinkheightlinkerlinkerimage'
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('enableShrinkingForCarouselItemItemImage', 'Symfony\Component\Form\Extension\Core\Type\CheckboxType', [
                'label' => $this->__('Enable shrinking for carousel item item image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Whether to enable shrinking huge images to maximum dimensions. Stores downscaled version of the original image.')
                ],
                'help' => $this->__('Whether to enable shrinking huge images to maximum dimensions. Stores downscaled version of the original image.'),
                'required' => false,
                'data' => (bool)$this->modVars['enableShrinkingForCarouselItemItemImage'],
                'attr' => [
                    'title' => $this->__('The enable shrinking for carousel item item image option.'),
                    'class' => 'shrink-enabler'
                ],
            ])
            ->add('shrinkWidthCarouselItemItemImage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Shrink width carousel item item image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The maximum image width in pixels.')
                ],
                'help' => $this->__('The maximum image width in pixels.'),
                'required' => false,
                'data' => $this->modVars['shrinkWidthCarouselItemItemImage'],
                'empty_data' => intval('800'),
                'attr' => [
                    'title' => $this->__('Enter the shrink width carousel item item image. Only digits are allowed.'),
                    'class' => 'shrinkdimension-shrinkwidthcarouselitemitemimage'
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('shrinkHeightCarouselItemItemImage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Shrink height carousel item item image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The maximum image height in pixels.')
                ],
                'help' => $this->__('The maximum image height in pixels.'),
                'required' => false,
                'data' => $this->modVars['shrinkHeightCarouselItemItemImage'],
                'empty_data' => intval('600'),
                'attr' => [
                    'title' => $this->__('Enter the shrink height carousel item item image. Only digits are allowed.'),
                    'class' => 'shrinkdimension-shrinkheightcarouselitemitemimage'
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('enableShrinkingForWebsiteImageMyImage', 'Symfony\Component\Form\Extension\Core\Type\CheckboxType', [
                'label' => $this->__('Enable shrinking for website image my image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Whether to enable shrinking huge images to maximum dimensions. Stores downscaled version of the original image.')
                ],
                'help' => $this->__('Whether to enable shrinking huge images to maximum dimensions. Stores downscaled version of the original image.'),
                'required' => false,
                'data' => (bool)$this->modVars['enableShrinkingForWebsiteImageMyImage'],
                'attr' => [
                    'title' => $this->__('The enable shrinking for website image my image option.'),
                    'class' => 'shrink-enabler'
                ],
            ])
            ->add('shrinkWidthWebsiteImageMyImage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Shrink width website image my image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The maximum image width in pixels.')
                ],
                'help' => $this->__('The maximum image width in pixels.'),
                'required' => false,
                'data' => $this->modVars['shrinkWidthWebsiteImageMyImage'],
                'empty_data' => intval('800'),
                'attr' => [
                    'title' => $this->__('Enter the shrink width website image my image. Only digits are allowed.'),
                    'class' => 'shrinkdimension-shrinkwidthwebsiteimagemyimage'
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('shrinkHeightWebsiteImageMyImage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Shrink height website image my image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The maximum image height in pixels.')
                ],
                'help' => $this->__('The maximum image height in pixels.'),
                'required' => false,
                'data' => $this->modVars['shrinkHeightWebsiteImageMyImage'],
                'empty_data' => intval('600'),
                'attr' => [
                    'title' => $this->__('Enter the shrink height website image my image. Only digits are allowed.'),
                    'class' => 'shrinkdimension-shrinkheightwebsiteimagemyimage'
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailModeLinker', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', [
                'label' => $this->__('Thumbnail mode linker') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail mode (inset or outbound).')
                ],
                'help' => $this->__('Thumbnail mode (inset or outbound).'),
                'required' => false,
                'data' => $this->modVars['thumbnailModeLinker'],
                'empty_data' => 'inset',
                'attr' => [
                    'title' => $this->__('Choose the thumbnail mode linker.')
                ],'choices' => [
                    $this->__('Inset') => 'inset'
                    ,$this->__('Outbound') => 'outbound'
                ],
                'choices_as_values' => true,
                'multiple' => false
            ])
            ->add('thumbnailWidthLinkerLinkerImageView', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width linker linker image view') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on view pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on view pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailWidthLinkerLinkerImageView'],
                'empty_data' => intval('32'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width linker linker image view. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightLinkerLinkerImageView', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height linker linker image view') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on view pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on view pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailHeightLinkerLinkerImageView'],
                'empty_data' => intval('24'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height linker linker image view. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailWidthLinkerLinkerImageDisplay', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width linker linker image display') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on display pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on display pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailWidthLinkerLinkerImageDisplay'],
                'empty_data' => intval('240'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width linker linker image display. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightLinkerLinkerImageDisplay', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height linker linker image display') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on display pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on display pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailHeightLinkerLinkerImageDisplay'],
                'empty_data' => intval('180'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height linker linker image display. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailWidthLinkerLinkerImageEdit', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width linker linker image edit') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on edit pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on edit pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailWidthLinkerLinkerImageEdit'],
                'empty_data' => intval('240'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width linker linker image edit. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightLinkerLinkerImageEdit', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height linker linker image edit') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on edit pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on edit pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailHeightLinkerLinkerImageEdit'],
                'empty_data' => intval('180'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height linker linker image edit. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailModeCarouselItem', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', [
                'label' => $this->__('Thumbnail mode carousel item') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail mode (inset or outbound).')
                ],
                'help' => $this->__('Thumbnail mode (inset or outbound).'),
                'required' => false,
                'data' => $this->modVars['thumbnailModeCarouselItem'],
                'empty_data' => 'inset',
                'attr' => [
                    'title' => $this->__('Choose the thumbnail mode carousel item.')
                ],'choices' => [
                    $this->__('Inset') => 'inset'
                    ,$this->__('Outbound') => 'outbound'
                ],
                'choices_as_values' => true,
                'multiple' => false
            ])
            ->add('thumbnailWidthCarouselItemItemImageView', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width carousel item item image view') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on view pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on view pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailWidthCarouselItemItemImageView'],
                'empty_data' => intval('32'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width carousel item item image view. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightCarouselItemItemImageView', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height carousel item item image view') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on view pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on view pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailHeightCarouselItemItemImageView'],
                'empty_data' => intval('24'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height carousel item item image view. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailWidthCarouselItemItemImageDisplay', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width carousel item item image display') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on display pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on display pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailWidthCarouselItemItemImageDisplay'],
                'empty_data' => intval('240'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width carousel item item image display. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightCarouselItemItemImageDisplay', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height carousel item item image display') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on display pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on display pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailHeightCarouselItemItemImageDisplay'],
                'empty_data' => intval('180'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height carousel item item image display. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailWidthCarouselItemItemImageEdit', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width carousel item item image edit') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on edit pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on edit pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailWidthCarouselItemItemImageEdit'],
                'empty_data' => intval('240'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width carousel item item image edit. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightCarouselItemItemImageEdit', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height carousel item item image edit') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on edit pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on edit pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailHeightCarouselItemItemImageEdit'],
                'empty_data' => intval('180'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height carousel item item image edit. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailModeWebsiteImage', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', [
                'label' => $this->__('Thumbnail mode website image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail mode (inset or outbound).')
                ],
                'help' => $this->__('Thumbnail mode (inset or outbound).'),
                'required' => false,
                'data' => $this->modVars['thumbnailModeWebsiteImage'],
                'empty_data' => 'inset',
                'attr' => [
                    'title' => $this->__('Choose the thumbnail mode website image.')
                ],'choices' => [
                    $this->__('Inset') => 'inset'
                    ,$this->__('Outbound') => 'outbound'
                ],
                'choices_as_values' => true,
                'multiple' => false
            ])
            ->add('thumbnailWidthWebsiteImageMyImageView', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width website image my image view') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on view pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on view pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailWidthWebsiteImageMyImageView'],
                'empty_data' => intval('32'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width website image my image view. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightWebsiteImageMyImageView', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height website image my image view') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on view pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on view pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailHeightWebsiteImageMyImageView'],
                'empty_data' => intval('24'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height website image my image view. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailWidthWebsiteImageMyImageDisplay', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width website image my image display') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on display pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on display pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailWidthWebsiteImageMyImageDisplay'],
                'empty_data' => intval('240'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width website image my image display. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightWebsiteImageMyImageDisplay', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height website image my image display') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on display pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on display pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailHeightWebsiteImageMyImageDisplay'],
                'empty_data' => intval('180'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height website image my image display. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailWidthWebsiteImageMyImageEdit', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width website image my image edit') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on edit pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on edit pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailWidthWebsiteImageMyImageEdit'],
                'empty_data' => intval('240'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width website image my image edit. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightWebsiteImageMyImageEdit', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height website image my image edit') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on edit pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on edit pages in pixels.'),
                'required' => false,
                'data' => $this->modVars['thumbnailHeightWebsiteImageMyImageEdit'],
                'empty_data' => intval('180'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height website image my image edit. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'rkwebsitehelpermodule_appsettings';
    }
}
