<?php
/**
 * ParkHaus.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ParkHausModule\Form\Base;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use Zikula\ExtensionsModule\Api\VariableApi;

/**
 * Configuration form type base class.
 */
abstract class AbstractAppSettingsType extends AbstractType
{
    use TranslatorTrait;

    /**
     * @var VariableApi
     */
    protected $variableApi;

    /**
     * @var array
     */
    protected $modVars;

    /**
     * AppSettingsType constructor.
     *
     * @param TranslatorInterface $translator  Translator service instance
     * @param VariableApi         $variableApi VariableApi service instance
     */
    public function __construct(TranslatorInterface $translator, VariableApi $variableApi)
    {
        $this->setTranslator($translator);
        $this->variableApi = $variableApi;
        $this->modVars = $this->variableApi->getAll('RKParkHausModule');
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this->addOwnerRefreshFields($builder, $options);
        $this->addListviewsFields($builder, $options);
        $this->addImagesFields($builder, $options);

        $builder
            ->add('save', 'Symfony\Component\Form\Extension\Core\Type\SubmitType', [
                'label' => $this->__('Update configuration'),
                'icon' => 'fa-check',
                'attr' => [
                    'class' => 'btn btn-success'
                ]
            ])
            ->add('cancel', 'Symfony\Component\Form\Extension\Core\Type\SubmitType', [
                'label' => $this->__('Cancel'),
                'icon' => 'fa-times',
                'attr' => [
                    'class' => 'btn btn-default',
                    'formnovalidate' => 'formnovalidate'
                ]
            ])
        ;
    }

    /**
     * Adds fields for owner refresh fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addOwnerRefreshFields(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('myFlag', 'Symfony\Component\Form\Extension\Core\Type\CheckboxType', [
                'label' => $this->__('My flag') . ':',
                'required' => false,
                'data' => (bool)isset($this->modVars['myFlag']) ? $this->modVars['myFlag'] : '',
                'attr' => [
                    'title' => $this->__('The my flag option.')
                ],
            ])
        ;
    }

    /**
     * Adds fields for listviews fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addListviewsFields(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('vehicleEntriesPerPage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Vehicle entries per page') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The amount of vehicles shown per page')
                ],
                'help' => $this->__('The amount of vehicles shown per page'),
                'required' => false,
                'data' => isset($this->modVars['vehicleEntriesPerPage']) ? $this->modVars['vehicleEntriesPerPage'] : '',
                'empty_data' => intval('10'),
                'attr' => [
                    'title' => $this->__('Enter the vehicle entries per page. Only digits are allowed.')
                ],'max_length' => 255,
                'scale' => 0
            ])
            ->add('vehicleImageEntriesPerPage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Vehicle image entries per page') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The amount of vehicle images shown per page')
                ],
                'help' => $this->__('The amount of vehicle images shown per page'),
                'required' => false,
                'data' => isset($this->modVars['vehicleImageEntriesPerPage']) ? $this->modVars['vehicleImageEntriesPerPage'] : '',
                'empty_data' => intval('10'),
                'attr' => [
                    'title' => $this->__('Enter the vehicle image entries per page. Only digits are allowed.')
                ],'max_length' => 255,
                'scale' => 0
            ])
        ;
    }

    /**
     * Adds fields for images fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addImagesFields(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('enableShrinkingForVehicleTitleImage', 'Symfony\Component\Form\Extension\Core\Type\CheckboxType', [
                'label' => $this->__('Enable shrinking for vehicle title image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Whether to enable shrinking huge images to maximum dimensions. Stores downscaled version of the original image.')
                ],
                'help' => $this->__('Whether to enable shrinking huge images to maximum dimensions. Stores downscaled version of the original image.'),
                'required' => false,
                'data' => (bool)isset($this->modVars['enableShrinkingForVehicleTitleImage']) ? $this->modVars['enableShrinkingForVehicleTitleImage'] : '',
                'attr' => [
                    'title' => $this->__('The enable shrinking for vehicle title image option.'),
                    'class' => 'shrink-enabler'
                ],
            ])
            ->add('shrinkWidthVehicleTitleImage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Shrink width vehicle title image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The maximum image width in pixels.')
                ],
                'help' => $this->__('The maximum image width in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['shrinkWidthVehicleTitleImage']) ? $this->modVars['shrinkWidthVehicleTitleImage'] : '',
                'empty_data' => intval('800'),
                'attr' => [
                    'title' => $this->__('Enter the shrink width vehicle title image. Only digits are allowed.'),
                    'class' => 'shrinkdimension-shrinkwidthvehicletitleimage'
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('shrinkHeightVehicleTitleImage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Shrink height vehicle title image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The maximum image height in pixels.')
                ],
                'help' => $this->__('The maximum image height in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['shrinkHeightVehicleTitleImage']) ? $this->modVars['shrinkHeightVehicleTitleImage'] : '',
                'empty_data' => intval('600'),
                'attr' => [
                    'title' => $this->__('Enter the shrink height vehicle title image. Only digits are allowed.'),
                    'class' => 'shrinkdimension-shrinkheightvehicletitleimage'
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailModeVehicleTitleImage', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', [
                'label' => $this->__('Thumbnail mode vehicle title image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail mode (inset or outbound).')
                ],
                'help' => $this->__('Thumbnail mode (inset or outbound).'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailModeVehicleTitleImage']) ? $this->modVars['thumbnailModeVehicleTitleImage'] : '',
                'empty_data' => 'inset',
                'attr' => [
                    'title' => $this->__('Choose the thumbnail mode vehicle title image.')
                ],'choices' => [
                    $this->__('Inset') => 'inset'
                    ,$this->__('Outbound') => 'outbound'
                ],
                'choices_as_values' => true,
                'multiple' => false
            ])
            ->add('thumbnailWidthVehicleTitleImageView', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width vehicle title image view') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on view pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on view pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailWidthVehicleTitleImageView']) ? $this->modVars['thumbnailWidthVehicleTitleImageView'] : '',
                'empty_data' => intval('32'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width vehicle title image view. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightVehicleTitleImageView', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height vehicle title image view') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on view pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on view pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailHeightVehicleTitleImageView']) ? $this->modVars['thumbnailHeightVehicleTitleImageView'] : '',
                'empty_data' => intval('24'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height vehicle title image view. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailWidthVehicleTitleImageDisplay', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width vehicle title image display') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on display pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on display pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailWidthVehicleTitleImageDisplay']) ? $this->modVars['thumbnailWidthVehicleTitleImageDisplay'] : '',
                'empty_data' => intval('240'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width vehicle title image display. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightVehicleTitleImageDisplay', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height vehicle title image display') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on display pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on display pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailHeightVehicleTitleImageDisplay']) ? $this->modVars['thumbnailHeightVehicleTitleImageDisplay'] : '',
                'empty_data' => intval('180'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height vehicle title image display. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailWidthVehicleTitleImageEdit', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width vehicle title image edit') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on edit pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on edit pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailWidthVehicleTitleImageEdit']) ? $this->modVars['thumbnailWidthVehicleTitleImageEdit'] : '',
                'empty_data' => intval('240'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width vehicle title image edit. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightVehicleTitleImageEdit', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height vehicle title image edit') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on edit pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on edit pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailHeightVehicleTitleImageEdit']) ? $this->modVars['thumbnailHeightVehicleTitleImageEdit'] : '',
                'empty_data' => intval('180'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height vehicle title image edit. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('enableShrinkingForVehicleVehicleImage', 'Symfony\Component\Form\Extension\Core\Type\CheckboxType', [
                'label' => $this->__('Enable shrinking for vehicle vehicle image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Whether to enable shrinking huge images to maximum dimensions. Stores downscaled version of the original image.')
                ],
                'help' => $this->__('Whether to enable shrinking huge images to maximum dimensions. Stores downscaled version of the original image.'),
                'required' => false,
                'data' => (bool)isset($this->modVars['enableShrinkingForVehicleVehicleImage']) ? $this->modVars['enableShrinkingForVehicleVehicleImage'] : '',
                'attr' => [
                    'title' => $this->__('The enable shrinking for vehicle vehicle image option.'),
                    'class' => 'shrink-enabler'
                ],
            ])
            ->add('shrinkWidthVehicleVehicleImage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Shrink width vehicle vehicle image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The maximum image width in pixels.')
                ],
                'help' => $this->__('The maximum image width in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['shrinkWidthVehicleVehicleImage']) ? $this->modVars['shrinkWidthVehicleVehicleImage'] : '',
                'empty_data' => intval('800'),
                'attr' => [
                    'title' => $this->__('Enter the shrink width vehicle vehicle image. Only digits are allowed.'),
                    'class' => 'shrinkdimension-shrinkwidthvehiclevehicleimage'
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('shrinkHeightVehicleVehicleImage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Shrink height vehicle vehicle image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The maximum image height in pixels.')
                ],
                'help' => $this->__('The maximum image height in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['shrinkHeightVehicleVehicleImage']) ? $this->modVars['shrinkHeightVehicleVehicleImage'] : '',
                'empty_data' => intval('600'),
                'attr' => [
                    'title' => $this->__('Enter the shrink height vehicle vehicle image. Only digits are allowed.'),
                    'class' => 'shrinkdimension-shrinkheightvehiclevehicleimage'
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailModeVehicleVehicleImage', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', [
                'label' => $this->__('Thumbnail mode vehicle vehicle image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail mode (inset or outbound).')
                ],
                'help' => $this->__('Thumbnail mode (inset or outbound).'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailModeVehicleVehicleImage']) ? $this->modVars['thumbnailModeVehicleVehicleImage'] : '',
                'empty_data' => 'inset',
                'attr' => [
                    'title' => $this->__('Choose the thumbnail mode vehicle vehicle image.')
                ],'choices' => [
                    $this->__('Inset') => 'inset'
                    ,$this->__('Outbound') => 'outbound'
                ],
                'choices_as_values' => true,
                'multiple' => false
            ])
            ->add('thumbnailWidthVehicleVehicleImageView', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width vehicle vehicle image view') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on view pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on view pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailWidthVehicleVehicleImageView']) ? $this->modVars['thumbnailWidthVehicleVehicleImageView'] : '',
                'empty_data' => intval('32'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width vehicle vehicle image view. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightVehicleVehicleImageView', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height vehicle vehicle image view') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on view pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on view pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailHeightVehicleVehicleImageView']) ? $this->modVars['thumbnailHeightVehicleVehicleImageView'] : '',
                'empty_data' => intval('24'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height vehicle vehicle image view. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailWidthVehicleVehicleImageDisplay', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width vehicle vehicle image display') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on display pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on display pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailWidthVehicleVehicleImageDisplay']) ? $this->modVars['thumbnailWidthVehicleVehicleImageDisplay'] : '',
                'empty_data' => intval('240'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width vehicle vehicle image display. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightVehicleVehicleImageDisplay', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height vehicle vehicle image display') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on display pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on display pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailHeightVehicleVehicleImageDisplay']) ? $this->modVars['thumbnailHeightVehicleVehicleImageDisplay'] : '',
                'empty_data' => intval('180'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height vehicle vehicle image display. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailWidthVehicleVehicleImageEdit', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width vehicle vehicle image edit') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on edit pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on edit pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailWidthVehicleVehicleImageEdit']) ? $this->modVars['thumbnailWidthVehicleVehicleImageEdit'] : '',
                'empty_data' => intval('240'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width vehicle vehicle image edit. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightVehicleVehicleImageEdit', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height vehicle vehicle image edit') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on edit pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on edit pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailHeightVehicleVehicleImageEdit']) ? $this->modVars['thumbnailHeightVehicleVehicleImageEdit'] : '',
                'empty_data' => intval('180'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height vehicle vehicle image edit. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('enableShrinkingForVehicleManufacturerImage', 'Symfony\Component\Form\Extension\Core\Type\CheckboxType', [
                'label' => $this->__('Enable shrinking for vehicle manufacturer image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Whether to enable shrinking huge images to maximum dimensions. Stores downscaled version of the original image.')
                ],
                'help' => $this->__('Whether to enable shrinking huge images to maximum dimensions. Stores downscaled version of the original image.'),
                'required' => false,
                'data' => (bool)isset($this->modVars['enableShrinkingForVehicleManufacturerImage']) ? $this->modVars['enableShrinkingForVehicleManufacturerImage'] : '',
                'attr' => [
                    'title' => $this->__('The enable shrinking for vehicle manufacturer image option.'),
                    'class' => 'shrink-enabler'
                ],
            ])
            ->add('shrinkWidthVehicleManufacturerImage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Shrink width vehicle manufacturer image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The maximum image width in pixels.')
                ],
                'help' => $this->__('The maximum image width in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['shrinkWidthVehicleManufacturerImage']) ? $this->modVars['shrinkWidthVehicleManufacturerImage'] : '',
                'empty_data' => intval('800'),
                'attr' => [
                    'title' => $this->__('Enter the shrink width vehicle manufacturer image. Only digits are allowed.'),
                    'class' => 'shrinkdimension-shrinkwidthvehiclemanufacturerimage'
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('shrinkHeightVehicleManufacturerImage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Shrink height vehicle manufacturer image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The maximum image height in pixels.')
                ],
                'help' => $this->__('The maximum image height in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['shrinkHeightVehicleManufacturerImage']) ? $this->modVars['shrinkHeightVehicleManufacturerImage'] : '',
                'empty_data' => intval('600'),
                'attr' => [
                    'title' => $this->__('Enter the shrink height vehicle manufacturer image. Only digits are allowed.'),
                    'class' => 'shrinkdimension-shrinkheightvehiclemanufacturerimage'
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailModeVehicleManufacturerImage', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', [
                'label' => $this->__('Thumbnail mode vehicle manufacturer image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail mode (inset or outbound).')
                ],
                'help' => $this->__('Thumbnail mode (inset or outbound).'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailModeVehicleManufacturerImage']) ? $this->modVars['thumbnailModeVehicleManufacturerImage'] : '',
                'empty_data' => 'inset',
                'attr' => [
                    'title' => $this->__('Choose the thumbnail mode vehicle manufacturer image.')
                ],'choices' => [
                    $this->__('Inset') => 'inset'
                    ,$this->__('Outbound') => 'outbound'
                ],
                'choices_as_values' => true,
                'multiple' => false
            ])
            ->add('thumbnailWidthVehicleManufacturerImageView', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width vehicle manufacturer image view') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on view pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on view pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailWidthVehicleManufacturerImageView']) ? $this->modVars['thumbnailWidthVehicleManufacturerImageView'] : '',
                'empty_data' => intval('32'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width vehicle manufacturer image view. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightVehicleManufacturerImageView', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height vehicle manufacturer image view') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on view pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on view pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailHeightVehicleManufacturerImageView']) ? $this->modVars['thumbnailHeightVehicleManufacturerImageView'] : '',
                'empty_data' => intval('24'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height vehicle manufacturer image view. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailWidthVehicleManufacturerImageDisplay', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width vehicle manufacturer image display') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on display pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on display pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailWidthVehicleManufacturerImageDisplay']) ? $this->modVars['thumbnailWidthVehicleManufacturerImageDisplay'] : '',
                'empty_data' => intval('240'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width vehicle manufacturer image display. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightVehicleManufacturerImageDisplay', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height vehicle manufacturer image display') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on display pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on display pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailHeightVehicleManufacturerImageDisplay']) ? $this->modVars['thumbnailHeightVehicleManufacturerImageDisplay'] : '',
                'empty_data' => intval('180'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height vehicle manufacturer image display. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailWidthVehicleManufacturerImageEdit', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width vehicle manufacturer image edit') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on edit pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on edit pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailWidthVehicleManufacturerImageEdit']) ? $this->modVars['thumbnailWidthVehicleManufacturerImageEdit'] : '',
                'empty_data' => intval('240'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width vehicle manufacturer image edit. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightVehicleManufacturerImageEdit', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height vehicle manufacturer image edit') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on edit pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on edit pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailHeightVehicleManufacturerImageEdit']) ? $this->modVars['thumbnailHeightVehicleManufacturerImageEdit'] : '',
                'empty_data' => intval('180'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height vehicle manufacturer image edit. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('enableShrinkingForVehicleImageVehicleImage', 'Symfony\Component\Form\Extension\Core\Type\CheckboxType', [
                'label' => $this->__('Enable shrinking for vehicle image vehicle image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Whether to enable shrinking huge images to maximum dimensions. Stores downscaled version of the original image.')
                ],
                'help' => $this->__('Whether to enable shrinking huge images to maximum dimensions. Stores downscaled version of the original image.'),
                'required' => false,
                'data' => (bool)isset($this->modVars['enableShrinkingForVehicleImageVehicleImage']) ? $this->modVars['enableShrinkingForVehicleImageVehicleImage'] : '',
                'attr' => [
                    'title' => $this->__('The enable shrinking for vehicle image vehicle image option.'),
                    'class' => 'shrink-enabler'
                ],
            ])
            ->add('shrinkWidthVehicleImageVehicleImage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Shrink width vehicle image vehicle image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The maximum image width in pixels.')
                ],
                'help' => $this->__('The maximum image width in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['shrinkWidthVehicleImageVehicleImage']) ? $this->modVars['shrinkWidthVehicleImageVehicleImage'] : '',
                'empty_data' => intval('800'),
                'attr' => [
                    'title' => $this->__('Enter the shrink width vehicle image vehicle image. Only digits are allowed.'),
                    'class' => 'shrinkdimension-shrinkwidthvehicleimagevehicleimage'
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('shrinkHeightVehicleImageVehicleImage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Shrink height vehicle image vehicle image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The maximum image height in pixels.')
                ],
                'help' => $this->__('The maximum image height in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['shrinkHeightVehicleImageVehicleImage']) ? $this->modVars['shrinkHeightVehicleImageVehicleImage'] : '',
                'empty_data' => intval('600'),
                'attr' => [
                    'title' => $this->__('Enter the shrink height vehicle image vehicle image. Only digits are allowed.'),
                    'class' => 'shrinkdimension-shrinkheightvehicleimagevehicleimage'
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailModeVehicleImageVehicleImage', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', [
                'label' => $this->__('Thumbnail mode vehicle image vehicle image') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail mode (inset or outbound).')
                ],
                'help' => $this->__('Thumbnail mode (inset or outbound).'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailModeVehicleImageVehicleImage']) ? $this->modVars['thumbnailModeVehicleImageVehicleImage'] : '',
                'empty_data' => 'inset',
                'attr' => [
                    'title' => $this->__('Choose the thumbnail mode vehicle image vehicle image.')
                ],'choices' => [
                    $this->__('Inset') => 'inset'
                    ,$this->__('Outbound') => 'outbound'
                ],
                'choices_as_values' => true,
                'multiple' => false
            ])
            ->add('thumbnailWidthVehicleImageVehicleImageView', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width vehicle image vehicle image view') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on view pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on view pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailWidthVehicleImageVehicleImageView']) ? $this->modVars['thumbnailWidthVehicleImageVehicleImageView'] : '',
                'empty_data' => intval('32'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width vehicle image vehicle image view. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightVehicleImageVehicleImageView', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height vehicle image vehicle image view') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on view pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on view pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailHeightVehicleImageVehicleImageView']) ? $this->modVars['thumbnailHeightVehicleImageVehicleImageView'] : '',
                'empty_data' => intval('24'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height vehicle image vehicle image view. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailWidthVehicleImageVehicleImageDisplay', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width vehicle image vehicle image display') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on display pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on display pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailWidthVehicleImageVehicleImageDisplay']) ? $this->modVars['thumbnailWidthVehicleImageVehicleImageDisplay'] : '',
                'empty_data' => intval('240'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width vehicle image vehicle image display. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightVehicleImageVehicleImageDisplay', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height vehicle image vehicle image display') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on display pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on display pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailHeightVehicleImageVehicleImageDisplay']) ? $this->modVars['thumbnailHeightVehicleImageVehicleImageDisplay'] : '',
                'empty_data' => intval('180'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height vehicle image vehicle image display. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailWidthVehicleImageVehicleImageEdit', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail width vehicle image vehicle image edit') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail width on edit pages in pixels.')
                ],
                'help' => $this->__('Thumbnail width on edit pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailWidthVehicleImageVehicleImageEdit']) ? $this->modVars['thumbnailWidthVehicleImageVehicleImageEdit'] : '',
                'empty_data' => intval('240'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail width vehicle image vehicle image edit. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
            ->add('thumbnailHeightVehicleImageVehicleImageEdit', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Thumbnail height vehicle image vehicle image edit') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Thumbnail height on edit pages in pixels.')
                ],
                'help' => $this->__('Thumbnail height on edit pages in pixels.'),
                'required' => false,
                'data' => isset($this->modVars['thumbnailHeightVehicleImageVehicleImageEdit']) ? $this->modVars['thumbnailHeightVehicleImageVehicleImageEdit'] : '',
                'empty_data' => intval('180'),
                'attr' => [
                    'title' => $this->__('Enter the thumbnail height vehicle image vehicle image edit. Only digits are allowed.')
                ],'max_length' => 4,
                'scale' => 0,
                'input_group' => ['right' => $this->__('pixels')]
            ])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'rkparkhausmodule_appsettings';
    }
}
