<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace RK\TeamModule\Form\Type\Finder;

use RK\TeamModule\Form\Type\Finder\Base\AbstractPersonFinderType;

/**
 * Person finder form type implementation class.
 */
class PersonFinderType extends AbstractPersonFinderType
{
    // feel free to extend the base form type class here
}
