<?php
/**
 * WebsiteHelper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\WebsiteHelperModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use RK\WebsiteHelperModule\Entity\WebsiteImageEntity;

/**
 * Event base class for filtering website image processing.
 */
class AbstractFilterWebsiteImageEvent extends Event
{
    /**
     * @var WebsiteImageEntity Reference to treated entity instance.
     */
    protected $websiteImage;

    public function __construct(WebsiteImageEntity $websiteImage)
    {
        $this->websiteImage = $websiteImage;
    }

    public function getWebsiteImage()
    {
        return $this->websiteImage;
    }
}
